# Generated by Django 4.2.11 on 2026-01-12 21:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('volume', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('issue', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('doi_url', models.URLField(blank=True)),
                ('description', wagtail.fields.RichTextField()),
                ('pages', models.PositiveIntegerField()),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('journal_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
